### ISSUE TITLE
Plugin breaks on having the package name in the package deps

### ISSUE THREAD

**Issue by Cadair** [spacetelescope/minimum_dependencies#30]
Since we moved to pyproject.toml with sunpy we have had this style of dependancies to reduce duplication in our dep lists: 

```toml
all = ["sunpy[asdf,dask,image,jpeg2000,map,net,timeseries,visualization]"]
tests = [
  "sunpy[all,opencv,spice]",
```
https://github.com/sunpy/sunpy/blob/7d3cc09fed175db7f8e384433a4c7a27295b6797/pyproject.toml#L89-L91

This as it is at the moment fails because we haven't got a minimum version there, but we also don't want to put the name of the package in the generated requirement output at all.
